# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countcal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='comment',
            field=models.CharField(default='_', max_length=200),
        ),
    ]
